// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agjjlghtizecmscvuwhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnampsZ2h0aXplY21zY3Z1d2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTAxMjIsImV4cCI6MjA3MTk2NjEyMn0.xTrpoAbzVF6Vu-MOGN97Y7ejAUgKpCMegVWHqWegw28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});